# Absorbing Markov Chains
[See Wikiepdia](https://en.wikipedia.org/wiki/Absorbing_Markov_chain) <br>
1) There is at least one absorving state and <br>
2) It is possible to go from any state to at least one absorbing state in a finite number of steps
$$  P=\begin{pmatrix}
Q & R\\ 
0 & I_{r}
\end{pmatrix} $$

## Example
$$
P = \begin{bmatrix}
0 & \frac{2}{3} & \frac{1}{3}  & 0 & 0\\ 
\frac{1}{7} & 0 & 0 & \frac{2}{7} & \frac{4}{7}\\ 
0 & 0 & 1 & 0 & 0\\ 
0 & 0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 0 & 1
\end{bmatrix}
$$
Rows 0 and 1 are transition sates <br>
Rows 2, 3, and 4 are absorbing states
$$
Q = \begin{bmatrix}
0 & \frac{2}{3} \\ 
\frac{1}{7} & 0 
\end{bmatrix} 
\; \; \; 
R = \begin{bmatrix}
\frac{1}{3}  & 0 & 0\\ 
0 & \frac{2}{7} & \frac{4}{7}
\end{bmatrix}
\; \; \; 
I_{r} = \begin{bmatrix}
1 & 0 & 0\\ 
0 & 1 & 0\\ 
0 & 0 & 1
\end{bmatrix}
$$


In [72]:
import numpy as np
import numpy.linalg as alg

In [73]:
P = np.array([[0, 2/3, 1/3, 0, 0],
              [1/7, 0, 0, 2/7, 4/7],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]])
# Below is another example matrix you could use
P2 = np.array([[1/2, 1/2, 0 ,0],
              [0, 1/2, 1/2, 0],
              [1/2, 0, 0, 1/2],
              [0, 0, 0, 1]])
print("P = {}".format(P))


P = [[ 0.          0.66666667  0.33333333  0.          0.        ]
 [ 0.14285714  0.          0.          0.28571429  0.57142857]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [ 0.          0.          0.          0.          1.        ]]


In [74]:
# Get sizing and dimensions
Psize = len(P)
for index, r in enumerate(P):
    if r[index] == 1:
        absorbingStates = Psize - index
        break
Qsize = Psize - absorbingStates        

In [75]:
Q = P[0:Qsize, 0:Qsize]
R = P[0:Qsize, Qsize:]
Ir = np.identity(absorbingStates)

print("Q = {}".format(Q))
print("R = {}".format(R))
print("Ir = {}".format(Ir))

Q = [[ 0.          0.66666667]
 [ 0.14285714  0.        ]]
R = [[ 0.33333333  0.          0.        ]
 [ 0.          0.28571429  0.57142857]]
Ir = [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### Fundamental Matrix
$$ N = (I_{t} - Q)^{-1} $$
Where $N_{i, j}$ is the expected number of times the chain visits state $j$ when starting in state $i$.

In [76]:
It = np.identity(Qsize)
N = alg.inv(It - Q)
print("N = {}".format(N))


N = [[ 1.10526316  0.73684211]
 [ 0.15789474  1.10526316]]


### Expected Number of Steps
$$t = N1$$
Where $t_{i}$ is the expected number of steps before being absorbed when starting in transient state $i$.

In [77]:
one = np.ones(Qsize)
t = np.matmul(N,one)
print("t = {}".format(t))

t = [ 1.84210526  1.26315789]


### Absorbing Probabilities
$$ B = NR $$
Where $B_{i, j}$ is the probability of ending in absorbing state $j$ when starting in transient state $i$.

In [78]:
B = np.matmul(N,R)
print("B = {}".format(B))

B = [[ 0.36842105  0.21052632  0.42105263]
 [ 0.05263158  0.31578947  0.63157895]]
